name: CD - Deploy API (Legacy) & Clients

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'  

jobs:
  api:
    name: API (Legacy)
    runs-on: ubuntu-22.04
    permissions:
      deployments: write
      contents: read
    environment:
      name: prod-api-legacy
    steps:
      - name: Checkout Source Files
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: 'recursive'

      - uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Deploy API
        # [NOTE] Use backslashes for expansion on remote machine, example: \$NVM_DIR, etc.
        run: |
          set -e
          echo -e '\nLOG:Building...'
          pnpm i -g verdaccio
          verdaccio & (
            NPM_CONFIG_REGISTRY=http://localhost:4873 pnpm install && \
            pnpm prebuild && \
            pnpm build:curriculum && \
            pnpm build:server && \
            echo -e '\nLOG:Build completed.'
          )

      - name: Archive Release packages
        shell: bash
        run: |
          date=$(date '+%Y%m%d%H%M%S')
          7z a -t7z -mx -m0=LZMA2 -v40m verdaccio-packages-$date.7z /home/runner/.local/share/verdaccio/         

      - name: create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz.*
            verdaccio-packages*
          tag_name: ${{ github.event.inputs.tags }}

